spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: root
   # driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # h2:
  #  console.enabled: true